version: '3.8'

services:
  backend:
    image: back-img 
    container_name: backend-container
    ports:
      - "3000:3000" 
    networks:
      - app-network 

  frontend:
    image: front-img  
    container_name: frontend-container
    ports:
      - "5173:5173"  
    depends_on:
      - backend 
    networks:
      - app-network 

networks:
  app-network: 
    driver: bridge
