version: '3.9'
services:
  backend:
    build: ./back
    ports:
      - "3000:3000"
    restart: always

  frontend:
    build: ./front
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: always
